project:
  type: book

book:
  title: "pyStatQuest"
  author: "Yao-Chung Chen"
  date: "2022/8/19"
  chapters:
    - index.qmd
    - posts/pca/pca.qmd
    - posts/logistic_regression/logistic_regression.qmd
    - posts/likelihood/likelihood.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: journal
  pdf:
    documentclass: scrreprt



